"""Initial migration

Revision ID: a6ea32a79b2f
Revises: 
Create Date: 2025-03-21 12:23:38.876040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6ea32a79b2f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=256), nullable=False),
    sa.Column('refresh_token', sa.String(length=256), nullable=False),
    sa.Column('token_uri', sa.String(length=256), nullable=False),
    sa.Column('client_id', sa.String(length=256), nullable=False),
    sa.Column('client_secret', sa.String(length=256), nullable=False),
    sa.Column('scopes', sa.String(length=256), nullable=False),
    sa.Column('expiry', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('refresh_token'),
    sa.UniqueConstraint('token')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('sms_service_activated', sa.Boolean(), nullable=True),
    sa.Column('temperature_service_activate', sa.Boolean(), nullable=True),
    sa.Column('humidity_service_activate', sa.Boolean(), nullable=True),
    sa.Column('temperature_treshold', sa.Float(), nullable=False),
    sa.Column('humidity_treshold', sa.Float(), nullable=False),
    sa.Column('reminder_delay', sa.Integer(), nullable=False),
    sa.Column('reminder_unit', sa.String(length=10), nullable=True),
    sa.Column('token_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['token_id'], ['token.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('token_id')
    )
    op.create_table('event_notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_notification')
    op.drop_table('user')
    op.drop_table('token')
    # ### end Alembic commands ###
